version: "3"
services:

  scurm_time_calc:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: scurm_time
    volumes:
      - ./:/app
    restart: always
    ports:
      - "5000:80"

    logging:
      driver: "json-file"
      options:
        max-size: "50m"




